#pragma once

#define CHIP8_SCREEN_WIDTH      64
#define CHIP8_SCREEN_HEIGHT     32
#define CHIP8_WINDOW_SCALE      18
#define CHIP8_WINDOW_WIDTH      CHIP8_SCREEN_WIDTH * CHIP8_WINDOW_SCALE
#define CHIP8_WINDOW_HEIGHT     CHIP8_SCREEN_HEIGHT * CHIP8_WINDOW_SCALE
#define CHIP8_WINDOW_TITLE      "Chip8 Emulator"

#define CHIP8_MEMORY_SIZE       4096
#define CHIP8_REGISTER_COUNT    16
#define CHIP8_STACK_DEPTH       16
#define CHIP8_TOTAL_KEYS        16
#define CHIP8_TIMER_RATE_NS     16666666
#define CHIP8_CLOCK_RATE_NS     1428571

#define CHIP8_CHARSET_ADDRESS       0x000
#define CHIP8_PROGRAM_LOAD_ADDRESS  0x200 