#pragma once

#define CHIP8_WINDOW_WIDTH     64
#define CHIP8_WINDOW_HEIGHT    32
#define CHIP8_WINDOW_SCALE      10
#define CHIP8_DISPLAY_WIDTH      CHIP8_WINDOW_WIDTH * CHIP8_WINDOW_SCALE
#define CHIP8_DISPLAY_HEIGHT     CHIP8_WINDOW_HEIGHT * CHIP8_WINDOW_SCALE
#define CHIP8_WINDOW_TITLE      "Chip8 Emulator"

#define CHIP8_MEMORY_SIZE       4096
#define CHIP8_REGISTER_COUNT    16
#define CHIP8_STACK_DEPTH       16
#define CHIP8_TOTAL_KEYS        16